# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_sub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sub_title',
        ),
    ]
